### PR TITLE
pt-PT 1.0.1

### PR DESCRIPTION
**Pull request by ptopenweb**
pt-PT with all new lang vars translated
version updated

### CODE REVIEW

**Comment by Oleg-SA** [comment]
I want to add a translation in the Russian language. Can I do this without a desktop program for windows? I'm just here for the first time. And did not understand everything. Please tell me what should I do. I want put in the directory yjsg-translations
  3 files:
ru-RU.plg_system_yjsg.sys.ini
ru-RU.plg_system_yjsg.ini
install.xml

But I can not provide them with a folder named "ru-RU" to put them there. Who can sdet it? Help out!

**Comment by danyj** [comment]
@Oleg-SA  Sorry bud but you need to get to know the git. In order to track changes and keep up with updates anyone that wants to be involved needs to learn how to use github. 

I know is bit complicated for beginner but once you get the hang of 2/3 commands it is easy. 
Download git for windows
https://windows.github.com/
Here some useful links
https://help.github.com/articles/getting-started-with-github-for-windows/
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by ptopenweb** [comment]
I use github for windows, this is how i did it:
1. First, online, create a fork of 'yjsg-transations' repository to your github account (use "fork" button in top right corner)
2. Then download github for windows and install
3. After install, click the "+" sign and select "clone" tab and clone your repository (your fork) to your computer. It will install it in the directory you select
4. Make the changes you need in that directory (add/edit/remove dirs, files, etc)
5. Once your done, go back to github for windows, and select the repository 'yjsg-transations', you will see "uncommited changes'. Click "show" and add a title and description of your commit and then 'commit to master' (this will commit your changes to your fork in your computer)
6. Now, still on github for windows, press "Sync" top right corner (this will sync your fork on your computer with your fork on online github)
7. Now you can go to your fork in your online github account. It will say that you are ahead of master (you're fork is ahead of youjommla master)
8. Make a pull request (theres a link for that) and they will automaticly go to youjoomla master (in pending approval)
9. If youjoomla aproves it it will be merged in the main code
(you may need to repeat 4 to 9 process if changes are needed)

And yes as danyj said it's a bit tricky at the beggining but after is very good

**Comment by Oleg-SA** [comment]
Thanks for the tips and gentlemen! I got it! But I can not live set, for his work needed NET. Framework 4.5.
Download it tomorrow will do everything according to instructions, as you advised.

**Comment by danyj** [comment]
@Oleg-SA test on this repo first , add , remove , fork etc
https://github.com/octocat/Spoon-Knife
you will get a hang of it fast. And yes , follow ptopenweb instructions, they are dead on. 

But the way I did is I separated my Github dir, 
http://screencast.com/t/PuUWWv7FAcut
http://screencast.com/t/3m4mHCCRBrr
worked on a extra joomla install specially dedicated for testing 
http://screencast.com/t/amXbODR8
once I am done , I copy/paste files from testing install to GitHub repos and than open git for Windows which tells me that there were changes to the files. 
This way I make sure my git repo holder is clean.

**Comment by Oleg-SA** [comment]
Thank you for your help and advice. Tomorrow I will lift Windows 7 in a virtual machine on your computer, which runs on windows XP. Git is not installed on XP it is outdated. Then put Git following your instructions, and you see what I got. Now I have a 4:37 AM and needed to go to bed. Today, after 4 hours still to go to work.

Until tomorrow, gentlemen.

**Pull request merged**
