### PR TITLE
Added translation YJSG Template Framework Plugin into Russian:

### PR DESCRIPTION
**Pull request by Oleg-SA**
Translated the following files:

-ru-RU.plg_system_yjsg.sys.ini
-ru-RU.plg_system_yjsg.ini
-install.xml

Translate version 1.0.0

### CODE REVIEW

**Comment by danyj** [comment]
do me a favor please, commit to your repo first so that we can see the correct structure on your side
meaning you should have ru-RU  folder here 
https://github.com/Oleg-SA/yjsg-translations

**Comment by Oleg-SA** [comment]
Until now, I did not put the folder Udall ru-RU here:
https://github.com/Oleg-SA/yjsg-транслатионс
It is here:
https://github.com/Oleg-SA/yjsg-translations/tree/ru-RU 

I continue to experiment with branches. I still do not fully understand the software TortoiseGit. It is very extensive and confusing. But everything comes with experience ....

**Comment by Oleg-SA** [comment]
It seems I was able to add a folder ru-RU in https://github.com/Oleg-SA/yjsg-translations. Can you see it?

**Comment by danyj** [comment]
yes we are testing this. will reply once done

**Comment by danyj** [comment]
do you mind showing admin screen translated in Russian please. We installed RU and your lang but yours is not taking over. Portuguese version that we have in this repo works fine. 
http://screencast.com/t/qLl0PzLE

**Comment by danyj** [comment]
You have a bug somewhere , 
if I leave only this string in RU file it works 
COM_TEMPLATES_YJSG_STYLE_SETTINGS_FIELDSET_LABEL="Стиль"
http://screencast.com/t/iaWP6LXTF

Please make sure you see the translations properly before submitting.

**Comment by mikimaus144** [comment]
I tried to instal russian language but it seems to have some bug, I am not able to see russian language in template administration, it is 2.5 version that I am talking about...

**Comment by danyj** [comment]
And the strings should be done correctly 
https://github.com/YJSGframework/yjsg-translations/blob/master/en-GB/en-GB.plg_system_yjsg.ini#L763

see that href is all lowercase 

yours is uppercase
https://github.com/Oleg-SA/yjsg-translations/blob/ru-RU/ru-RU/ru-RU.plg_system_yjsg.ini#L763

Just looking at the color code of the file on git I see bugs 
look here 
https://github.com/Oleg-SA/yjsg-translations/blob/ru-RU/ru-RU/ru-RU.plg_system_yjsg.ini#L739

all lang strings  should be purple on git
many of yours are red starting from line 143 and down.

**Pull request closed without merging**
